const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const html=fs.readFileSync('app/src/main/assets/lyrics_overlay.html','utf8');
const context={translationMode:'bilingual',pronunciationEnabled:false};
vm.createContext(context);
vm.runInContext(html.slice(html.indexOf('    const escapeHtml ='),html.indexOf('    function formatTime(')),context);
vm.runInContext(html.slice(html.indexOf('    function parseLrc('),html.indexOf('    function renderLyrics(')),context);
const lines=context.parseLrc('[00:01]君のとなり\n[00:05]未来へ向かう');
let aligned=context.attachTranslations(lines,'[00:01.1]kimi no tonari\n[00:05]mirai e mukau','pronunciation');
aligned=context.attachTranslations(aligned,'[00:01]在你身旁\n[00:05]走向未来');
assert.equal(aligned[0].pronunciation,'kimi no tonari');
assert.equal(aligned[1].translation,'走向未来');
assert.equal(context.attachTranslations(lines,'[00:15]unrelated','pronunciation')[0].pronunciation,'');
assert.ok(!context.lineHtml(aligned[0]).includes('line-pronunciation'));
context.pronunciationEnabled=true;
assert.match(context.lineHtml(aligned[0]),/kimi no tonari/);
assert.match(context.lineHtml(aligned[0]),/在你身旁/);
const rendered=context.lineHtml(aligned[0]);
assert.ok(rendered.indexOf('line-pronunciation')<rendered.indexOf('line-original'));
assert.ok(rendered.indexOf('line-original')<rendered.indexOf('line-translation'));
assert.equal(context.compactSupplement(aligned[0]),'在你身旁');
context.translationMode='original';
assert.equal(context.compactSupplement(aligned[0]),'');
context.translationMode='translated';
assert.equal(context.linePrimaryText(aligned[0]),'在你身旁');
assert.equal(context.compactSupplement(aligned[0]),'');
context.pronunciationEnabled=false;
assert.equal(context.compactSupplement(aligned[0]),'');
context.pronunciationEnabled=true;
assert.match(context.lineHtml({text:'君',pronunciation:'<img src=x onerror=alert(1)>'}),/&lt;img/);
assert.ok(!context.lineHtml({text:'君',pronunciation:'<img src=x onerror=alert(1)>'}).includes('<img'));
console.log('PASS: aligned readings, missing data, independent translation modes, compact supplements, HTML escaping');
